import type { Metadata } from 'next'
import { Be_Vietnam_Pro } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import ContextProvider from './context/context-provider'

const be_Vietnam_Pro = Be_Vietnam_Pro({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Country Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ContextProvider>
      <html lang="en">
        <body className={`${be_Vietnam_Pro.className} bg-[#18191b] flex justify-center`}>
            <Image className='z-0 absolute w-full' priority width={1000} height={1000} src='/hero-image-wr.jpg' alt='hero image' />
            <Image className='z-10 absolute pt-[10%] left-[50%] -translate-x-[50%] w-auto h-auto' width={100} height={100} src='/Logo.svg' alt='hero image' />
          {children}
        </body>
      </html>
    </ContextProvider>
  )
}
